export const INDIAN_SCHOOLS = [
  "Air Force Bal Bharati School, New Delhi",
  "Army Public School, New Delhi",
  "Bal Bharati Public School, New Delhi",
  "Bishop Cotton School, Shimla",
  "Bishops Co-Ed School, Pune",
  "Campion School, Mumbai",
  "Cathedral and John Connon School, Mumbai",
  "Central Hindu School, Varanasi",
  "Chinmaya Vidyalaya, Chennai",
  "Convent of Jesus and Mary, New Delhi",
  "DAV Public School, New Delhi",
  "Delhi Public School, New Delhi",
  "Delhi Public School, R.K. Puram",
  "Don Bosco High School, Mumbai",
  "Doon School, Dehradun",
  "Fr. Agnel Multipurpose School, Mumbai",
  "Frank Anthony Public School, Bangalore",
  "GD Goenka Public School, Gurgaon",
  "Greenwood High School, Bangalore",
  "Indian School, Muscat",
  "Inventure Academy, Bangalore",
  "Jawahar Navodaya Vidyalaya",
  "Kendriya Vidyalaya",
  "La Martiniere Girls' School, Kolkata",
  "Lakshmipat Singhania Academy, Kolkata",
  "Loreto House, Kolkata",
  "Mayo College, Ajmer",
  "Modern High School for Girls, Kolkata",
  "Modern School, Barakhamba Road, New Delhi",
  "Mother's International School, New Delhi",
  "Mount Carmel School, New Delhi",
  "Mount Litera Zee School",
  "New Era Public School, New Delhi",
  "Nirmala Convent School, Vijayawada",
  "Notre Dame Academy, Patna",
  "Podar International School, Mumbai",
  "Pratap Public School, Bikaner",
  "Presidency School, Bangalore",
  "Rajkumar College, Raipur",
  "Ryan International School",
  "Sacred Heart Convent School, Chandigarh",
  "Sardar Patel Vidyalaya, New Delhi",
  "Scottish High International School, Gurgaon",
  "Scindia School, Gwalior",
  "Shiv Nadar School",
  "Springdales School, New Delhi",
  "St. Columba's School, New Delhi",
  "St. Francis De Sales School, Nagpur",
  "St. Joseph's Boys' High School, Bangalore",
  "St. Mary's School, Pune",
  "St. Paul's School, Darjeeling",
  "St. Stephen's School, New Delhi",
  "St. Thomas' Boys' School, Kolkata",
  "St. Xavier's High School, Mumbai",
  "St. Xavier's School, Kolkata",
  "Sunbeam School, Varanasi",
  "Symbiosis International School, Pune",
  "Tagorean International School, Delhi",
  "The Heritage School, Kolkata",
  "The Lawrence School, Sanawar",
  "The Millennium School",
  "The Orchid School, Pune",
  "Tula's International School, Dehradun",
  "Utpal Shanghvi Global School, Mumbai",
  "Vasant Valley School, New Delhi",
  "Vidyashram The Schoolhouse, Jaipur",
  "Welham Boys' School, Dehradun",
  "Welham Girls' School, Dehradun",
  "Woodstock School, Mussoorie",
  "Other",
];
